version: '3.1'
services:
  # db:
  #   image: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: test_db
  #   ports:
  #     - "3308:3306"
  nextstop:
    image: nunomelo/nextstop:9.0
    restart: always
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: secret
      MYSQL_HOST: nextstopbd
      MYSQL_DATABASE: autocarro
    ports:
      - "8080"